### PR TITLE
Add the all-important .gitattributes file

### PR DESCRIPTION
**Pull request by AArnott**
Otherwise, various configurations of local git clients will fight over line endings.

This takes the one-time hit after adding .gitattributes to make all file line endings consistent. Only 3 files needed fixing.

### CODE REVIEW

**Comment by gep13** [comment]
@AArnott quick question, as I have thought about making a similar change in other repos....

What was required to apply the line ending changes to the files?  Or did git take care of this automagically?  Also, how to decide what is the best practice for what goes into the gitattributes file?

Thanks!

**Comment by AArnott** [comment]
> how to decide what is the best practice for what goes into the gitattributes file?

This is the standard template file that most git clients recommend. It's mostly comments as you can see. The only significant line is near the top, which gives git the permission to detect text files and normalize line endings for them. It's the right setting for almost all repos because it makes it so that regardless of your text editor or operating system, the text files have the right line endings for the developer. 

Before this change, I would open some of your text files and VS would warn me that there are inconsistent line endings even within the same file. This will never happen again with this .gitattributes file in place.

> What was required to apply the line ending changes to the files? Or did git take care of this automagically? 

git does _not_ take care of it automatically. But almost. If you _just_ add .gitattributes, git will occasionally discover another text file that was encoded wrong and claim the whole file changed and block many of your git operations until you let it do its thing. It's quite annoying when it just pops up like that and distracting in code reviews and git history.
So to force git to recognize and fix them all at once, as I've done, I ran these commands:

```
git clean -fdx :/
git rm --cached -r :/
git add :/ -A -f
git commit -m "Reconcile line endings"
```

**Comment by gep13** [comment]
@AArnott thank you very much for the information.  I need to do this on a number of other repos 😄

**Comment by AArnott** [comment]
No problem. Read more about it [here](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings)

**Pull request merged**
