### PR TITLE
[WIP] MSBuild GitLink Task

### PR DESCRIPTION
**Pull request by distantcam**
Ok here's the GitLink MSBuild task.

The NuGet package still needs to be built for this. The files should be in the following paths:

\Build\dotnet\GitLink.targets
\GitLinkTask.dll
\GitLinkTask.pdb

Also in the root directory put GitLink.exe and dependencies.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Thanks a lot! I need to review a few other PRs first, but I'll put it on the list. Much appreciated!

**Comment by GeertvanHorrik** [comment]
Sorry I let this one slip, my bad. Will review this one soon.

**Comment by GeertvanHorrik** [comment]
Finished the implementation, now available as prerelease on NuGet. Thanks @distantcam !

**Comment by distantcam** [comment]
@GeertvanHorrik Unfortunately the nuget has the binary in the wrong location. The nuget should look like this.

\Build\dotnet\GitLink.targets
\GitLinkTask.dll
\GitLinkTask.pdb
\GitLink.exe

**Comment by GeertvanHorrik** [comment]
@distantcam So only GitLink.exe is missing, right? Then I will add that one

**Comment by distantcam** [comment]
@GeertvanHorrik No. Also GitLinkTask.dll and pdb need to be taken out of Lib and put in the root of the nuget.

**Comment by GeertvanHorrik** [comment]
Build - 2.4.0-unstable.9 should fix this. Thanks for letting us know!

**Pull request merged**
